"""Create user table

Revision ID: 11997f02eabe
Revises: e3b93d71ba43
Create Date: 2018-11-29 15:31:05.572990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11997f02eabe'
down_revision = 'e3b93d71ba43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=280), nullable=True),
    sa.Column('apitoken', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
